"""inicial_tablas

Revision ID: 3da5310dd269
Revises: 
Create Date: 2026-03-23 15:56:04.644016

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '3da5310dd269'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('razon_social', sa.String(length=200), nullable=True),
    sa.Column('ruc', sa.String(length=11), nullable=True),
    sa.Column('direccion_fiscal', sa.Text(), nullable=True),
    sa.Column('yape_numero', sa.String(length=15), nullable=True),
    sa.Column('plin_numero', sa.String(length=15), nullable=True),
    sa.Column('cuenta_bcp', sa.String(length=30), nullable=True),
    sa.Column('cuenta_bbva', sa.String(length=30), nullable=True),
    sa.Column('radio_busqueda_km', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('nubefact_token', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('locales',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('direccion', sa.Text(), nullable=False),
    sa.Column('lat', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('lng', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('foto_url', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('celular', sa.String(length=15), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('dni', sa.String(length=15), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.Enum('cliente', 'admin', name='rolenum'), nullable=False),
    sa.Column('fcm_token', sa.String(length=300), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_celular'), 'users', ['celular'], unique=True)
    op.create_table('canchas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('local_id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('capacidad', sa.SmallInteger(), nullable=False),
    sa.Column('precio_hora', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('superficie', sa.String(length=50), nullable=True),
    sa.Column('foto_url', sa.Text(), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['local_id'], ['locales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notificaciones',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('tipo', sa.String(length=40), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('leida', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('horarios_disponibles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cancha_id', sa.Uuid(), nullable=False),
    sa.Column('dia_semana', sa.SmallInteger(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.Column('precio_override', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cancha_id'], ['canchas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reservas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('codigo', sa.String(length=12), nullable=False),
    sa.Column('cliente_id', sa.Uuid(), nullable=False),
    sa.Column('cancha_id', sa.Uuid(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.Column('precio_total', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('estado', sa.Enum('pending', 'confirmed', 'active', 'done', 'canceled', name='estadoreservaenum'), nullable=False),
    sa.Column('tipo_doc', sa.Enum('boleta', 'factura', name='tipodocenum'), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('timer_inicio', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timer_fin', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cancha_id'], ['canchas.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cancha_id', 'fecha', 'hora_inicio', name='uq_reserva_slot'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('comprobantes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('reserva_id', sa.Uuid(), nullable=False),
    sa.Column('cliente_id', sa.Uuid(), nullable=False),
    sa.Column('tipo', sa.Enum('boleta', 'factura', name='tipocomprobanteenum'), nullable=False),
    sa.Column('serie', sa.String(length=5), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('igv', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('ruc_receptor', sa.String(length=15), nullable=True),
    sa.Column('razon_receptor', sa.String(length=200), nullable=True),
    sa.Column('nubefact_id', sa.Text(), nullable=True),
    sa.Column('xml_firmado_url', sa.Text(), nullable=True),
    sa.Column('pdf_url', sa.Text(), nullable=True),
    sa.Column('estado', sa.Enum('pendiente', 'emitido', 'error', name='estadocomprobanteenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reserva_id'], ['reservas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pagos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('reserva_id', sa.Uuid(), nullable=False),
    sa.Column('cliente_id', sa.Uuid(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('metodo', sa.Enum('yape', 'plin', 'transferencia', 'efectivo', 'tarjeta', name='metodopagoenum'), nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'verificado', 'rechazado', name='estadopagoenum'), nullable=False),
    sa.Column('voucher_url', sa.Text(), nullable=True),
    sa.Column('comprobante_ext', sa.String(length=60), nullable=True),
    sa.Column('verificado_por', sa.Uuid(), nullable=True),
    sa.Column('verificado_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reserva_id'], ['reservas.id'], ),
    sa.ForeignKeyConstraint(['verificado_por'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pagos')
    op.drop_table('comprobantes')
    op.drop_table('reservas')
    op.drop_table('horarios_disponibles')
    op.drop_table('notificaciones')
    op.drop_table('canchas')
    op.drop_index(op.f('ix_users_celular'), table_name='users')
    op.drop_table('users')
    op.drop_table('locales')
    op.drop_table('configuracion')
    # ### end Alembic commands ###
