"""add_email_to_users

Revision ID: 4f4f8043c1a6
Revises: 92c71b2d552c
Create Date: 2026-03-29 21:15:35.045165

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '4f4f8043c1a6'
down_revision: Union[str, None] = '92c71b2d552c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('suscripciones', 'estado',
               existing_type=postgresql.ENUM('pendiente', 'activo', 'rechazado', 'vencido', name='estadosuscripcionenum'),
               nullable=False,
               existing_server_default=sa.text("'pendiente'::estadosuscripcionenum"))
    op.alter_column('suscripciones', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('users', sa.Column('email', sa.String(length=150), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'email')
    op.alter_column('suscripciones', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('suscripciones', 'estado',
               existing_type=postgresql.ENUM('pendiente', 'activo', 'rechazado', 'vencido', name='estadosuscripcionenum'),
               nullable=True,
               existing_server_default=sa.text("'pendiente'::estadosuscripcionenum"))
    # ### end Alembic commands ###
