// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIBDKwugvWYH9s7A2KYZdq7lboyxNAK_k',
    appId: '1:83990636031:web:da3dec3a2653e9de1473ca',
    messagingSenderId: '83990636031',
    projectId: 'pichangaya-6d300',
    storageBucket: 'pichangaya-6d300.firebasestorage.app',
    authDomain: 'pichangaya-6d300.firebaseapp.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3r2lHGRxH-y_j6t5MK13CQ1XXPAfiLY4',
    appId: '1:83990636031:android:f2107e573a6d42d51473ca',
    messagingSenderId: '83990636031',
    projectId: 'pichangaya-6d300',
    storageBucket: 'pichangaya-6d300.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYwqmGXDqJpCc0TMcn4lmJWsgci6BAgjg',
    appId: '1:83990636031:ios:56427f2fa9a104c71473ca',
    messagingSenderId: '83990636031',
    projectId: 'pichangaya-6d300',
    storageBucket: 'pichangaya-6d300.firebasestorage.app',
    iosBundleId: 'com.pichangaya.app',
  );
}
